using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "e10afc777d3a8c89")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.6")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Base</summary>
	[PublishedContentModel("Base")]
	public partial class Base : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Base";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Base(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Base, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Background Color
		///</summary>
		[ImplementPropertyType("bgColor")]
		public object BgColor
		{
			get { return this.GetPropertyValue("bgColor"); }
		}

		///<summary>
		/// Class Name
		///</summary>
		[ImplementPropertyType("className")]
		public string ClassName
		{
			get { return this.GetPropertyValue<string>("className"); }
		}

		///<summary>
		/// Hide From Sitemap
		///</summary>
		[ImplementPropertyType("hideFromSitemap")]
		public bool HideFromSitemap
		{
			get { return this.GetPropertyValue<bool>("hideFromSitemap"); }
		}

		///<summary>
		/// Hide From Navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}
	}

	/// <summary>Base Page</summary>
	[PublishedContentModel("BasePage")]
	public partial class BasePage : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BasePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BasePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BasePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// OG Description
		///</summary>
		[ImplementPropertyType("ogDescription")]
		public string OgDescription
		{
			get { return this.GetPropertyValue<string>("ogDescription"); }
		}

		///<summary>
		/// OG Image
		///</summary>
		[ImplementPropertyType("ogImage")]
		public string OgImage
		{
			get { return this.GetPropertyValue<string>("ogImage"); }
		}

		///<summary>
		/// OG Title
		///</summary>
		[ImplementPropertyType("ogTitle")]
		public string OgTitle
		{
			get { return this.GetPropertyValue<string>("ogTitle"); }
		}

		///<summary>
		/// Redirect to page
		///</summary>
		[ImplementPropertyType("redirectToPage")]
		public object RedirectToPage
		{
			get { return this.GetPropertyValue("redirectToPage"); }
		}

		///<summary>
		/// Redirect to URL
		///</summary>
		[ImplementPropertyType("redirectToUrl")]
		public string RedirectToUrl
		{
			get { return this.GetPropertyValue<string>("redirectToUrl"); }
		}

		///<summary>
		/// Tags
		///</summary>
		[ImplementPropertyType("tags")]
		public object Tags
		{
			get { return this.GetPropertyValue("tags"); }
		}
	}

	/// <summary>Carousel Item</summary>
	[PublishedContentModel("CarouselItem")]
	public partial class CarouselItem : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "CarouselItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("img")]
		public string Img
		{
			get { return this.GetPropertyValue<string>("img"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public object Link
		{
			get { return this.GetPropertyValue("link"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Carousel Module</summary>
	[PublishedContentModel("CarouselModule")]
	public partial class CarouselModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "CarouselModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public IHtmlString Header
		{
			get { return this.GetPropertyValue<IHtmlString>("header"); }
		}
	}

	/// <summary>Collapsible List Item</summary>
	[PublishedContentModel("CollapsibleListItem")]
	public partial class CollapsibleListItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "CollapsibleListItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CollapsibleListItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CollapsibleListItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Tab Content
		///</summary>
		[ImplementPropertyType("tabContent")]
		public IHtmlString TabContent
		{
			get { return this.GetPropertyValue<IHtmlString>("tabContent"); }
		}

		///<summary>
		/// Tab Name
		///</summary>
		[ImplementPropertyType("tabName")]
		public string TabName
		{
			get { return this.GetPropertyValue<string>("tabName"); }
		}
	}

	/// <summary>Collapsible List Module</summary>
	[PublishedContentModel("CollapsibleListModule")]
	public partial class CollapsibleListModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "CollapsibleListModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CollapsibleListModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CollapsibleListModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}
	}

	/// <summary>Page</summary>
	[PublishedContentModel("Page")]
	public partial class Page : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Page";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Page(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Page, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Page Header Background Color
		///</summary>
		[ImplementPropertyType("headerBgColor")]
		public object HeaderBgColor
		{
			get { return this.GetPropertyValue("headerBgColor"); }
		}

		///<summary>
		/// Page Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public string PageBanner
		{
			get { return this.GetPropertyValue<string>("pageBanner"); }
		}

		///<summary>
		/// Page Header
		///</summary>
		[ImplementPropertyType("pageHeader")]
		public IHtmlString PageHeader
		{
			get { return this.GetPropertyValue<IHtmlString>("pageHeader"); }
		}

		///<summary>
		/// Page Header Text Color
		///</summary>
		[ImplementPropertyType("pageHeaderTextColor")]
		public object PageHeaderTextColor
		{
			get { return this.GetPropertyValue("pageHeaderTextColor"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Contact Page</summary>
	[PublishedContentModel("ContactPage")]
	public partial class ContactPage : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ContactPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address Panel
		///</summary>
		[ImplementPropertyType("addressPanel")]
		public IHtmlString AddressPanel
		{
			get { return this.GetPropertyValue<IHtmlString>("addressPanel"); }
		}

		///<summary>
		/// Lead
		///</summary>
		[ImplementPropertyType("lead")]
		public IHtmlString Lead
		{
			get { return this.GetPropertyValue<IHtmlString>("lead"); }
		}

		///<summary>
		/// Right Panel
		///</summary>
		[ImplementPropertyType("rightPanel")]
		public IHtmlString RightPanel
		{
			get { return this.GetPropertyValue<IHtmlString>("rightPanel"); }
		}
	}

	/// <summary>Empty Row Module</summary>
	[PublishedContentModel("EmptyRowModule")]
	public partial class EmptyRowModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "EmptyRowModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EmptyRowModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EmptyRowModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}
	}

	/// <summary>Four Column Module</summary>
	[PublishedContentModel("FourColumnModule")]
	public partial class FourColumnModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "FourColumnModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FourColumnModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FourColumnModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Column Four Text
		///</summary>
		[ImplementPropertyType("columnFourText")]
		public IHtmlString ColumnFourText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnFourText"); }
		}

		///<summary>
		/// Column One Text
		///</summary>
		[ImplementPropertyType("columnOneText")]
		public IHtmlString ColumnOneText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnOneText"); }
		}

		///<summary>
		/// Column Three Text
		///</summary>
		[ImplementPropertyType("columnThreeText")]
		public IHtmlString ColumnThreeText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnThreeText"); }
		}

		///<summary>
		/// Column Two Text
		///</summary>
		[ImplementPropertyType("columnTwoText")]
		public IHtmlString ColumnTwoText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnTwoText"); }
		}

		///<summary>
		/// Font Color
		///</summary>
		[ImplementPropertyType("fontColor")]
		public object FontColor
		{
			get { return this.GetPropertyValue("fontColor"); }
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("footer")]
		public IHtmlString Footer
		{
			get { return this.GetPropertyValue<IHtmlString>("footer"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public IHtmlString Header
		{
			get { return this.GetPropertyValue<IHtmlString>("header"); }
		}
	}

	/// <summary>Home Page</summary>
	[PublishedContentModel("HomePage")]
	public partial class HomePage : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "HomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contact Email Message
		///</summary>
		[ImplementPropertyType("contactEmailMsg")]
		public IHtmlString ContactEmailMsg
		{
			get { return this.GetPropertyValue<IHtmlString>("contactEmailMsg"); }
		}

		///<summary>
		/// Download Email Message
		///</summary>
		[ImplementPropertyType("downloadEmailMsg")]
		public IHtmlString DownloadEmailMsg
		{
			get { return this.GetPropertyValue<IHtmlString>("downloadEmailMsg"); }
		}

		///<summary>
		/// Footer Links
		///</summary>
		[ImplementPropertyType("footerLinks")]
		public object FooterLinks
		{
			get { return this.GetPropertyValue("footerLinks"); }
		}

		///<summary>
		/// Page Header Background Color
		///</summary>
		[ImplementPropertyType("headerBgColor")]
		public object HeaderBgColor
		{
			get { return this.GetPropertyValue("headerBgColor"); }
		}

		///<summary>
		/// LinkedIn URL
		///</summary>
		[ImplementPropertyType("linkedinUrl")]
		public string LinkedinUrl
		{
			get { return this.GetPropertyValue<string>("linkedinUrl"); }
		}

		///<summary>
		/// Newsletter Email Message
		///</summary>
		[ImplementPropertyType("newsletterEmailMsg")]
		public IHtmlString NewsletterEmailMsg
		{
			get { return this.GetPropertyValue<IHtmlString>("newsletterEmailMsg"); }
		}

		///<summary>
		/// Page Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public string PageBanner
		{
			get { return this.GetPropertyValue<string>("pageBanner"); }
		}

		///<summary>
		/// Page Header
		///</summary>
		[ImplementPropertyType("pageHeader")]
		public IHtmlString PageHeader
		{
			get { return this.GetPropertyValue<IHtmlString>("pageHeader"); }
		}

		///<summary>
		/// Page Header Text Color
		///</summary>
		[ImplementPropertyType("pageHeaderTextColor")]
		public object PageHeaderTextColor
		{
			get { return this.GetPropertyValue("pageHeaderTextColor"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("siteDescription")]
		public string SiteDescription
		{
			get { return this.GetPropertyValue<string>("siteDescription"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return this.GetPropertyValue<string>("siteName"); }
		}

		///<summary>
		/// Twitter ID
		///</summary>
		[ImplementPropertyType("twitterID")]
		public string TwitterID
		{
			get { return this.GetPropertyValue<string>("twitterID"); }
		}
	}

	/// <summary>Quick Nav Group</summary>
	[PublishedContentModel("QuickNavGroup")]
	public partial class QuickNavGroup : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "QuickNavGroup";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public QuickNavGroup(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<QuickNavGroup, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Quick Nav Item</summary>
	[PublishedContentModel("QuickNavItem")]
	public partial class QuickNavItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "QuickNavItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public QuickNavItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<QuickNavItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Call to Action
		///</summary>
		[ImplementPropertyType("callToAction")]
		public string CallToAction
		{
			get { return this.GetPropertyValue<string>("callToAction"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public object Link
		{
			get { return this.GetPropertyValue("link"); }
		}
	}

	/// <summary>Quick Nav Module</summary>
	[PublishedContentModel("QuickNavModule")]
	public partial class QuickNavModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "QuickNavModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public QuickNavModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<QuickNavModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("body")]
		public IHtmlString Body
		{
			get { return this.GetPropertyValue<IHtmlString>("body"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public IHtmlString Header
		{
			get { return this.GetPropertyValue<IHtmlString>("header"); }
		}

		///<summary>
		/// Nav Title
		///</summary>
		[ImplementPropertyType("navTitle")]
		public IHtmlString NavTitle
		{
			get { return this.GetPropertyValue<IHtmlString>("navTitle"); }
		}
	}

	/// <summary>Single Column Module</summary>
	[PublishedContentModel("SingleColumnModule")]
	public partial class SingleColumnModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SingleColumnModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SingleColumnModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SingleColumnModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Column One Text
		///</summary>
		[ImplementPropertyType("columnOneText")]
		public IHtmlString ColumnOneText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnOneText"); }
		}

		///<summary>
		/// Font Color
		///</summary>
		[ImplementPropertyType("fontColor")]
		public object FontColor
		{
			get { return this.GetPropertyValue("fontColor"); }
		}
	}

	/// <summary>Slider Module</summary>
	[PublishedContentModel("SliderModule")]
	public partial class SliderModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SliderModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SliderModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SliderModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Slider Module Slide</summary>
	[PublishedContentModel("SliderModuleSlide")]
	public partial class SliderModuleSlide : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SliderModuleSlide";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SliderModuleSlide(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SliderModuleSlide, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public string Image
		{
			get { return this.GetPropertyValue<string>("image"); }
		}

		///<summary>
		/// Image Link
		///</summary>
		[ImplementPropertyType("imageLink")]
		public object ImageLink
		{
			get { return this.GetPropertyValue("imageLink"); }
		}

		///<summary>
		/// Text
		///</summary>
		[ImplementPropertyType("textContent")]
		public IHtmlString TextContent
		{
			get { return this.GetPropertyValue<IHtmlString>("textContent"); }
		}
	}

	/// <summary>Three Column Module</summary>
	[PublishedContentModel("ThreeColumnModule")]
	public partial class ThreeColumnModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ThreeColumnModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ThreeColumnModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ThreeColumnModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Column One Text
		///</summary>
		[ImplementPropertyType("columnOneText")]
		public IHtmlString ColumnOneText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnOneText"); }
		}

		///<summary>
		/// Column Three Text
		///</summary>
		[ImplementPropertyType("columnThreeText")]
		public IHtmlString ColumnThreeText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnThreeText"); }
		}

		///<summary>
		/// Column Two Text
		///</summary>
		[ImplementPropertyType("columnTwoText")]
		public IHtmlString ColumnTwoText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnTwoText"); }
		}

		///<summary>
		/// Font Color
		///</summary>
		[ImplementPropertyType("fontColor")]
		public object FontColor
		{
			get { return this.GetPropertyValue("fontColor"); }
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("footer")]
		public IHtmlString Footer
		{
			get { return this.GetPropertyValue<IHtmlString>("footer"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public IHtmlString Header
		{
			get { return this.GetPropertyValue<IHtmlString>("header"); }
		}
	}

	/// <summary>Two Column Module</summary>
	[PublishedContentModel("TwoColumnModule")]
	public partial class TwoColumnModule : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "TwoColumnModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TwoColumnModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TwoColumnModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Column One Text
		///</summary>
		[ImplementPropertyType("columnOneText")]
		public IHtmlString ColumnOneText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnOneText"); }
		}

		///<summary>
		/// Column Two Text
		///</summary>
		[ImplementPropertyType("columnTwoText")]
		public IHtmlString ColumnTwoText
		{
			get { return this.GetPropertyValue<IHtmlString>("columnTwoText"); }
		}

		///<summary>
		/// Font Color
		///</summary>
		[ImplementPropertyType("fontColor")]
		public object FontColor
		{
			get { return this.GetPropertyValue("fontColor"); }
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("footer")]
		public IHtmlString Footer
		{
			get { return this.GetPropertyValue<IHtmlString>("footer"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public IHtmlString Header
		{
			get { return this.GetPropertyValue<IHtmlString>("header"); }
		}
	}

	/// <summary>People Item</summary>
	[PublishedContentModel("peopleItem")]
	public partial class PeopleItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "peopleItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PeopleItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PeopleItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public string Image
		{
			get { return this.GetPropertyValue<string>("image"); }
		}

		///<summary>
		/// Location
		///</summary>
		[ImplementPropertyType("location")]
		public string Location
		{
			get { return this.GetPropertyValue<string>("location"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>People Page</summary>
	[PublishedContentModel("peoplePage")]
	public partial class PeoplePage : Page
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "peoplePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PeoplePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PeoplePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Page Lead
		///</summary>
		[ImplementPropertyType("pageLead")]
		public IHtmlString PageLead
		{
			get { return this.GetPropertyValue<IHtmlString>("pageLead"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
